[workspace]
members = [
  "crates/kernel",
  "crates/platform",
  "crates/logging",
  "crates/sysapi",
  "crates/boot",
  "crates/bootloader-uefi",
  "crates/boot-protocol",
  "crates/vm",
  "crates/drivers",
  "crates/installer",
  "crates/init",
  "crates/ui",
  "crates/services",
  "services/sadas-core",
  "services/permission-broker",
  "services/privacy-firewall",
  "apps/sadas-store",
  "apps/sadas-settings",
  "tools/sadasctl",
  "tools/qemu-runner"
]
resolver = "2"

[workspace.package]
edition = "2021"
authors = ["Sadas OS Contributors"]
license = "MIT"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
